#!/usr/bin/env python3
"""Create paper-ready model-comparison visuals from real CPU benchmark outputs."""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
INPUT = ROOT / "evidence" / "embedding_benchmark"
FIGS = ROOT / "paper" / "figs"
TABLES = ROOT / "paper" / "tables"
FIGS.mkdir(exist_ok=True)
TABLES.mkdir(exist_ok=True)

MODEL_LABELS = {
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2": "Multilingual MiniLM-L12",
    "sentence-transformers/all-MiniLM-L6-v2": "English MiniLM-L6",
}
COLORS = {
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2": "#0072B2",
    "sentence-transformers/all-MiniLM-L6-v2": "#D55E00",
}


def main() -> None:
    frames = [pd.read_csv(path) for path in INPUT.glob("*/scope_summary.csv")]
    if len(frames) < 2:
        raise RuntimeError("Expected completed results for two models")
    data = pd.concat(frames, ignore_index=True)
    data = data[data["query_tag"].eq("phrase")].copy()

    fig, axes = plt.subplots(2, 2, figsize=(10.2, 6.8), sharex="col", constrained_layout=True)
    language_names = {"en": "English phrase query", "zh": "Chinese phrase query"}
    for col, lang in enumerate(("en", "zh")):
        subset = data[data["lang"].eq(lang)]
        for model, group in subset.groupby("model"):
            group = group.sort_values("extra_docs")
            label = MODEL_LABELS[model]
            color = COLORS[model]
            axes[0, col].plot(group["extra_docs"], group["iaea_priority_top10_mean"],
                              marker="o", lw=2.2, color=color, label=label)
            axes[0, col].fill_between(group["extra_docs"],
                                      group["iaea_priority_top10_mean"] - group["iaea_priority_top10_std"].fillna(0),
                                      group["iaea_priority_top10_mean"] + group["iaea_priority_top10_std"].fillna(0),
                                      color=color, alpha=0.14)
            axes[1, col].plot(group["extra_docs"], group["top1_score_mean"],
                              marker="o", lw=2.2, color=color, label=label)
        axes[0, col].set_title(language_names[lang])
        axes[0, col].set_ylim(-0.03, 1.05)
        axes[0, col].set_ylabel("IAEA priority@10")
        axes[1, col].set_ylabel("Top-1 cosine score")
        axes[1, col].set_xlabel("Supplementary documents admitted")
        for row in range(2):
            axes[row, col].grid(alpha=0.24)
    axes[0, 0].legend(frameon=False, loc="upper right")
    fig.savefig(FIGS / "fig7_real_embedding_comparison.pdf", bbox_inches="tight")
    fig.savefig(FIGS / "fig7_real_embedding_comparison.png", dpi=300, bbox_inches="tight")
    plt.close(fig)

    rows = []
    for model, label in MODEL_LABELS.items():
        for lang in ("en", "zh"):
            for extra in (0, 10, 51):
                row = data[(data["model"].eq(model)) & (data["lang"].eq(lang)) & (data["extra_docs"].eq(extra))].iloc[0]
                rows.append((label, "English" if lang == "en" else "Chinese", extra,
                             row["iaea_priority_top10_mean"], row["iaea_priority_top10_std"], row["top1_score_mean"]))
    latex = [
        "% Generated by scripts/build_embedding_comparison.py from actual CPU benchmark results.",
        "\\begin{table}[t]", "  \\centering",
        "  \\caption{Real embedding-model comparison under the new CPU benchmark (64 documents, 13 IAEA core documents, 11,199 chunks, 10 random trials after corpus expansion). This benchmark uses 240-word chunks and is reported separately from the historical nomic-embed-text index.}",
        "  \\label{tab:real-embedding-comparison}", "  \\small", "  \\resizebox{\\linewidth}{!}{%",
        "  \\begin{tabular}{llccc}", "    \\toprule",
        "    Model & Query language & Supplementary documents & IAEA priority@10 & Top-1 cosine \\\\", "    \\midrule",
    ]
    for model, lang, extra, priority, std, score in rows:
        latex.append(f"    {model} & {lang} & {extra} & {priority:.2f} $\\pm$ {0.0 if pd.isna(std) else std:.2f} & {score:.2f} \\\\")
    latex += ["    \\bottomrule", "  \\end{tabular}", "  }", "\\end{table}", ""]
    (TABLES / "table_real_embedding_comparison.tex").write_text("\n".join(latex), encoding="utf-8")
    print("Wrote", FIGS / "fig7_real_embedding_comparison.pdf")


if __name__ == "__main__":
    main()
